INSERT INTO `nodes` (`id`, `lft`, `rght`, `parent_id`, `status`, `comment_level`, `edit_level`, `depth`, `sequence`, `created`, `modified`) VALUES
(1, 1, 6, NULL, 1, 200, 600, 0, '', '2008-01-16 17:08:41', '2008-07-09 20:09:59'),
(2, 2, 5, 1, 1, 200, 600, 1, '', '2008-01-16 17:08:41', '2008-07-09 20:09:59'),
(3, 3, 4, 2, 1, 200, 200, 2, '', '2008-01-16 17:08:41', '2008-07-09 20:09:59');

--
-- Dumping data for table `revisions`
--

INSERT INTO `revisions` (`id`, `node_id`, `under_node_id`, `after_node_id`, `status`, `user_id`, `lang`, `slug`, `title`, `content`, `type`, `reason`, `flags`, `created`, `modified`) VALUES
(1, 2, 0, 0, 'current', 1, 'en', '1-2-collection', '1.2 Collection', '<p>All things related to CakePHP version 1.2</p>', NULL, NULL, '', '2008-02-19 01:30:18', '2008-02-19 01:30:19'),
(2, 1, 0, 0, 'current', 1, 'en', 'collection-index', 'Collection index', '<p>All you ever wanted to know about CakePHP.</p>', NULL, '', '', '2008-07-01 07:56:33', '2008-07-01 11:17:48'),
(3, 3, 0, 0, 'current', 1, 'en', 'the-manual', 'The Manual', '<p><strong><a href="http://book.cakephp.org/view/305/the-manual">Click here for the CakePHP 1.1.x version of the manual</a></strong></p>\r\n\r\n<p>Welcome to the Cookbook, the CakePHP documentation. The Cookbook is a wiki-like system allowing contributions from the public. With an open system, we hope to maintain a high level of quality, validity, and accuracy for the CakePHP documentation. The Cookbook also makes it easy for anybody to contribute.</p>\r\n\r\n<p>A <em><strong>huge</strong></em> thank you  to <a href="http://www.ad7six.com/" title="Mi Blog">AD7six</a>, who championed the Cookbook by putting in endless hours developing, testing and improving this application.</p>\r\n<h4>How it Works:</h4>\r\n<ol>\r\n	<li>You visit the site and notice an error, something that is incomplete, something that hasn''t been covered at all, or something that just isn''t worded to your liking.</li>\r\n	<li>Log in to Cookbook using your <a href="http://bakery.cakephp.org" title="The Bakery: Everything CakePHP">Bakery</a> account.</li>\r\n	<li>Submit additions/edits for review using valid, semantic HTML.</li>\r\n	<li>Check back in the next day or so to see your changes approved.</li>\r\n        <li>Please review <a href="http://manual.cakephp.org/view/482/contributing-to-the-cookbook">the guidelines for submitting to the Cookbook</a> to ensure consistency.</li>\r\n</ol>\r\n<br/>\r\n<h4>Translations</h4>\r\n<p>Email John David Anderson (docs at cakephp dot org) or on IRC (#cakephp on freenode as _psychic_) to discuss any translation efforts you would like to participate in.</p>\r\n<p>Translator tips:</p>\r\n<ul>\r\n	<li>Do not use <a href="http://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references" title="What Are HTML Entities?">html entities</a> for accented characters, the book uses UTF-8.</li>\r\n	<li>Use <a href="http://en.wikipedia.org/wiki/Register_%28linguistics%29" title="What is Informal Form?">Informal Form</a>.</li>\r\n	<li>Translate both the content and the title at the same time.</li>\r\n	<li>Browse and edit in the language the content is being translated to - otherwise it get''s logged as an English Edit with only a slim chance that a reviewer knows what language you are writing in.</li>\r\n</ul>\r\n<br />\r\n<p>We''re committed to making the documentation for CakePHP better than it has ever been. We hope you''ll join us by using the Cookbook and giving back to a project that we''ve all benefited so much from.</p>', NULL, 'I changed the title', '', '2008-07-08 10:43:59', '2008-07-09 11:06:38');

